Edit ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -32,6 +32,11 @@ jobs:
         working-directory: dagster_nyt_books
         run: black .
 
-      - name: Run linting
+      - name: Run type checking
         working-directory: dagster_nyt_books
-        run: flake8 .
+        run: | 
+          mypy . || true                            # Run mypy on the codebase, allow it to fail
+          mypy --install-types --non-interactive    # Install missing types automatically
+          mypy .                                    # Run mypy again after installing types
+
+
